configure:
  languages:
{{- if eq .Computed.javascript "true" }}
    javascript: true
{{- end}}

lint:
  aspects:
{{- if eq .Computed.javascript "true" }}
    - //tools/lint:linters.bzl%eslint
{{- end }}
{{- if eq .Computed.python "true" }}
    - //tools/lint:linters.bzl%ruff
{{- end }}
