configure:
  languages:
{{- if .Computed.go }}
    go: true
{{- end }}
{{- if .Computed.javascript }}
    javascript: true
{{- end }}
{{- if .Scaffold.protobuf }}
    protobuf: true
{{- end }}
{{- if .Scaffold.python }}
    python: true
{{- end }}

{{- if .Scaffold.lint }}
lint:
  aspects:
    - //tools/lint:linters.bzl%shellcheck
{{- if .Computed.javascript }}
    - //tools/lint:linters.bzl%eslint
{{- end }}
{{- if .Computed.python }}
    - //tools/lint:linters.bzl%ruff
{{- end }}
{{- end }}
