on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:        
    test:
        strategy:
            matrix:
                preset:
                    - kitchen-sink
                    - js
                    - py
                    - minimal
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v5
              with:
                go-version: '>=1.22'
            - uses: bazel-contrib/setup-bazel@0.8.2
              with:
                bazelisk-cache: true
                repository-cache: true 
            - run: go install github.com/hay-kot/scaffold@v0.0.90
            - name: Scaffold new app
              id: scaffold
              run: |
                scaffold new --preset=${{ matrix.preset }} --no-prompt $GITHUB_WORKSPACE
                cd scaffold_test*
                git init
                echo "::set-output name=dir::$PWD"
            - name: Test
              working-directory: "${{ steps.scaffold.outputs.dir }}"
              run: bazel test ...
            - name: Format
              working-directory: "${{ steps.scaffold.outputs.dir }}"
              if: "${{ matrix.preset != 'minimal' }}"
              run: bazel run format
            - name: Lint
              working-directory: "${{ steps.scaffold.outputs.dir }}"
              if: "${{ matrix.preset == 'py' || matrix.preset == 'js' }}"
              run: bazel lint //...
